<?php

/**
 * Implements hook_ckeditor_plugin().
 */
function ubc_ckeditor_plugins_ckeditor_plugin() {
    return array(
        'accordion' => array(
          'name' => 'accordion',
          'desc' => t('Widget to insert an accordion.'),
          'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/accordion/',
          'buttons' => array(
            'accordion' => array(
              'label' => 'Insert Accordion',
              'icon' => 'icon-accordion.png',
            ),
          ),
        ),
        'accordiontoggle' => array(
          'name' => 'accordiontoggle',
          'desc' => t('Widget to insert an accordion toggle for all accordions on the page.'),
          'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/accordiontoggle/',
          'buttons' => array(
            'accordiontoggle' => array(
              'label' => 'Insert Accordion Open / Close All Button',
              'icon' => 'icon-accordiontoggle.png',
            ),
          ),
        ),
        'callout' => array(
            'name' => 'callout',
            'desc' => t('Widget to insert a callout.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/callout/',
            'buttons' => array(
                'callout' => array(
                    'label' => 'Insert Callout',
                    'icon' => 'callout.png',
                ),
            ),
        ),
        'media-object' => array(
            'name' => 'media-object',
            'desc' => t('Widget to insert a media object.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/media-object/',
            'buttons' => array(
                'media-object' => array(
                    'label' => 'Insert Media Object',
                    'icon' => 'media-object.png',
                ),
            ),
        ),
        'twocolumns' => array(
            'name' => 'twocolumns',
            'desc' => t('Widget to insert 2 Bootstrap v.2 columns.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/twocolumns/',
            'buttons' => array(
                'twocolumns' => array(
                    'label' => 'Insert 2 Bootstrap v.2 Columns',
                    'icon' => 'twocolumns.png',
                ),
            ),
        ),
        'threecolumns' => array(
            'name' => 'threecolumns',
            'desc' => t('Widget to insert 3 Bootstrap v.2 columns.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/threecolumns/',
            'buttons' => array(
                'threecolumns' => array(
                    'label' => 'Insert 3 Bootstrap v.2 Columns',
                    'icon' => 'threecolumns.png',
                ),
            ),
        ),
        'bs3-2columns' => array(
            'name' => 'bs3-2columns',
            'desc' => t('Widget to insert 2 columns.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/bs3-2columns/',
            'buttons' => array(
                'bs3-2columns' => array(
                    'label' => 'Insert 2 columns',
                    'icon' => 'bs3-2columns.png',
                ),
            ),
        ),
        'bs3-2columns-2-1' => array(
            'name' => 'bs3-2columns-2-1',
            'desc' => t('Widget to insert 2 columns (two thirds, then one third).'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/bs3-2columns-2-1/',
            'buttons' => array(
                'bs3-2columns-2-1' => array(
                    'label' => 'Insert 2 columns (two thirds, then one third)',
                    'icon' => 'bs3-2columns-2-1.png',
                ),
            ),
        ),
        'bs3-2columns-1-2' => array(
            'name' => 'bs3-2columns-1-2',
            'desc' => t('Widget to insert 2 columns (one third, then two thirds).'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/bs3-2columns-1-2/',
            'buttons' => array(
                'bs3-2columns-1-2' => array(
                    'label' => 'Insert 2 columns (one third, then two thirds)',
                    'icon' => 'bs3-2columns-1-2.png',
                ),
            ),
        ),
        'bs3-3columns' => array(
            'name' => 'bs3-3columns',
            'desc' => t('Widget to insert 3 columns.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/bs3-3columns/',
            'buttons' => array(
                'bs3-3columns' => array(
                    'label' => 'Insert 3 columns',
                    'icon' => 'bs3-3columns.png',
                ),
            ),
        ),
		'ctarow-two' => array(
            'name' => 'ctarow-two',
            'desc' => t('Widget to insert 2 Call To Action boxes.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/ctarow-two/',
            'buttons' => array(
                'ctarow-two' => array(
                    'label' => 'Insert 2 Call To Action boxes',
                    'icon' => 'ctarow-two.png',
                ),
            ),
        ),
        'ctarow-three' => array(
            'name' => 'ctarow-three',
            'desc' => t('Widget to insert 3 Call To Action boxes.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/ctarow-three/',
            'buttons' => array(
                'ctarow-three' => array(
                    'label' => 'Insert 3 Call To Action boxes',
                    'icon' => 'ctarow-three.png',
                ),
            ),
        ),
        'img-and-caption' => array(
            'name' => 'img-and-caption',
            'desc' => t('Widget to insert an image with a caption.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/img-and-caption/',
            'buttons' => array(
                'img-and-caption' => array(
                    'label' => 'Insert an image with a caption',
                    'icon' => 'img-and-caption.png',
                ),
            ),
        ),
		/*
        'fontawesome' => array(
            'name' => 'fontawesome',
            'desc' => t('Widget to insert a fontawesome icon.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/fontawesome/',
            'buttons' => array(
                'fontawesome' => array(
                    'label' => 'Insert a fontawesome icon',
                    'icon' => 'fontawesome.png',
                ),
            ),
        ),
		*/
		
		/*
        'btgrid' => array(
            'name' => 'btgrid',
            'desc' => t('Widget to insert a btgrid.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/btgrid/',
            'buttons' => array(
                'btgrid' => array(
                    'label' => 'Insert a btgrid',
                    'icon' => 'icons/btgrid.png',
                ),
            ),
        ),
		*/

		/*
        'listgroup' => array(
            'name' => 'listgroup',
            'desc' => t('Widget to insert a list-group button.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/listgroup/',
            'buttons' => array(
                'listgroup' => array(
                    'label' => 'Insert a list-group button',
                    'icon' => 'listgroup.png',
                ),
            ),
        ),
		*/

        'inline-counter' => array(
            'name' => 'inline-counter',
            'desc' => t('Widget to insert a inline counter.'),
            'path' => drupal_get_path('module', 'ubc_ckeditor_plugins') . '/plugins/inline-counter/',
            'buttons' => array(
                'inline-counter' => array(
                    'label' => 'Insert a inline-counter button',
                    'icon' => 'test.png',
                ),
            ),
        ),
		
    );
}

/**
 * Implements hook_entity_view().
 */
function ubc_ckeditor_plugins_entity_view($entity, $type, $view_mode, $langcode) {

    // Make the jQuery UI Accordion plugin available.
    drupal_add_library('system', 'ui.accordion');
    // Load our JS file that implements jQuery UI Accordion.
    drupal_add_js(drupal_get_path('module', 'ubc_ckeditor_plugins') . '/js/ubc_ckeditor_plugins.js');
	/*
	// don't remove empty span (needs to go on edit page - this is incorrect hook)
	drupal_add_js('CKEDITOR.dtd.$removeEmpty["span"] = false;',
	    array('type' => 'inline', 'scope' => 'header', 'group' => JS_DEFAULT, 'every_page' => TRUE, 'weight' => 10)
	  ); 
	*/

}
